[metadata]
name = bazel-build-file-sorter
version = 0.2.1
description = Sort targets in Bazel BUILD files (bundles the prebuilt Go binary)

[options]
python_requires = >=3.10
setup_requires =
    setuptools-download

[setuptools_download]
download_scripts =
    [bazel-build-file-sorter]
    group = bazel-build-file-sorter-binary
    marker = sys_platform == "darwin" and platform_machine == "arm64"
    url = https://github.com/ahans/bazel-build-file-sorter/releases/download/v0.2.1/build-file-sorter-darwin-arm64
    sha256 = 5bd7eebc57834261160df8800cbc73fbfedf004d2a1578279bb96bc54f0828b6
