[metadata]
name = bazel-build-file-sorter
version = 0.3.0
description = Sort targets in Bazel BUILD files (bundles the prebuilt Go binary)

[options]
python_requires = >=3.10
setup_requires =
    setuptools-download

[setuptools_download]
download_scripts =
    [bazel-build-file-sorter]
    group = bazel-build-file-sorter-binary
    marker = sys_platform == "linux" and platform_machine == "x86_64"
    url = https://github.com/ahans/bazel-build-file-sorter/releases/download/v0.3.0/bazel-build-file-sorter-linux-amd64
    sha256 = 3d278f5c178a1df889de9b30c8ab72e00fefedd8d7f7cb2f3ee5065bdb8312ba
    [bazel-build-file-sorter]
    group = bazel-build-file-sorter-binary
    marker = sys_platform == "linux" and platform_machine == "aarch64"
    url = https://github.com/ahans/bazel-build-file-sorter/releases/download/v0.3.0/bazel-build-file-sorter-linux-arm64
    sha256 = 476c1f189cfc8b57faaae60dbde08fed22bc6a0c41a8f2c5ddefaa47846156c0
    [bazel-build-file-sorter]
    group = bazel-build-file-sorter-binary
    marker = sys_platform == "darwin" and platform_machine == "x86_64"
    url = https://github.com/ahans/bazel-build-file-sorter/releases/download/v0.3.0/bazel-build-file-sorter-darwin-amd64
    sha256 = bc688016b436266aa811977735877041a6f44b70acc053f8d535f4dafcaa595e
    [bazel-build-file-sorter]
    group = bazel-build-file-sorter-binary
    marker = sys_platform == "darwin" and platform_machine == "arm64"
    url = https://github.com/ahans/bazel-build-file-sorter/releases/download/v0.3.0/bazel-build-file-sorter-darwin-arm64
    sha256 = 21095d81c95bec6d637ac0296fce7afd710293bf0d1a234bf0043c1a528587ed
    [bazel-build-file-sorter.exe]
    group = bazel-build-file-sorter-binary
    marker = sys_platform == "win32" and platform_machine == "AMD64"
    url = https://github.com/ahans/bazel-build-file-sorter/releases/download/v0.3.0/bazel-build-file-sorter-windows-amd64.exe
    sha256 = d42388c5282bcfd7c7fd59b6f3466c59b40076a626378bb6f6c8752444da47d2
    [bazel-build-file-sorter.exe]
    group = bazel-build-file-sorter-binary
    marker = sys_platform == "win32" and platform_machine == "ARM64"
    url = https://github.com/ahans/bazel-build-file-sorter/releases/download/v0.3.0/bazel-build-file-sorter-windows-arm64.exe
    sha256 = 1b55d4e6b6bff5a0e49a3f12bac25b7d2cbd07e00c31497ab3a2214923b0e482
